### ISSUE TITLE
eror while trying to compile the libraray 

### ISSUE THREAD

**Issue by Conansmith100** [libcpr/example-cmake-fetch-content#2]
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/ubuntu/cpr/build/example-cmake-fetch-content/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_32a60/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_32a60.dir/build.make CMakeFiles/cmTC_32a60.dir/build
    gmake[1]: Entering directory '/home/ubuntu/cpr/build/example-cmake-fetch-content/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_32a60.dir/testCCompiler.c.o
    /usr/bin/cc    -o CMakeFiles/cmTC_32a60.dir/testCCompiler.c.o -c /home/ubuntu/cpr/build/example-cmake-fetch-content/build/CMakeFiles/CMakeTmp/testCCompiler.c
    as: error while loading shared libraries: libcpr.so.1: cannot open shared object file: No such file or directory
    gmake[1]: *** [CMakeFiles/cmTC_32a60.dir/build.make:78: CMakeFiles/cmTC_32a60.dir/testCCompiler.c.o] Error 1
    gmake[1]: Leaving directory '/home/ubuntu/cpr/build/example-cmake-fetch-content/build/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_32a60/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

**Comment by COM8** [comment]
This is not a cpr issue. It's an issue of your system. `/usr/bin/cc` is not setup correctly. Nothing we can do here.
